services:
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - 8080:80
    depends_on:
      - localstack
      - mysql
      - awscli
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - adjoe

  test-task:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: adjoe-test/php
    networks:
      - adjoe
    depends_on:
      - localstack
      - mysql
      - awscli
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=adjoe
      - MYSQL_USER=adjoe
      - MYSQL_PASSWORD=adjoe
      - MYSQL_ROOT_PASSWORD=adjoe
    networks:
      - adjoe

  localstack:
    image: localstack/localstack:3.2
    user: root
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=eu-central-1
      - SERVICES=sqs
    ports:
      - 4566:4566
    networks:
      - adjoe

  awscli:
    depends_on:
      - localstack
    image: adjoe-test/awscli
    command: 'sqs create-queue --queue-name my-queue --region=eu-central-1 --endpoint-url="http://localstack:4566"'
    networks:
      - adjoe

networks:
  adjoe:
    name: adjoe-test
    driver: bridge

